### ISSUE TITLE
Using a default is detected as a model change

### ISSUE THREAD

**Issue by destos** [surenkov/django-pydantic-field#1]
When using a default and creating migrations it always detects the field as changed and regenerates migrations.

``` python
class BuildingTypes(str, Enum):
    FRAME = "frame"
    BRICK = "brick"
    STUCCO = "stucco"


class BuildingMeta(BaseModel):
    type: Optional[BuildingTypes]


default_meta = BuildingMeta(type=BuildingTypes.FRAME)


class Building(models.Model):
    meta = PydanticSchemaField(schema=BuildingMeta, default=default_meta)
```

This example should continue to create new migrations every time makemigrations is run for the app.

**Comment by surenkov** [comment]
Hi @destos, thank you for mentioning the problem with default values as pydantic model instances.

Usually this should not be an issue if you follow Django recommendations for [mutable objects as defaults](https://docs.djangoproject.com/en/4.1/ref/models/fields/#default). Essentially (even with `allow_mutation = False` schema config) all Pydantic objects are mutable, so you should not use their instances as `default=` values. The code below should work fine:
```python
def get_default_meta():
    return BuildingMeta(type=BuildingTypes.FRAME)

class Building(models.Model):
    meta = PydanticSchemaField(schema=BuildingMeta, default=get_default_meta)
```

Regardless of this recommedation, the behavior you described definitely not desirable. I'll try to get rid of it in the following update.

**Comment by destos** [comment]
@surenkov Ah, thanks, forgot about that. I had tried using a lambda but was still using the instance I already created and got the same results. 👍🏻

**Comment by surenkov** [comment]
Please check out v0.0.4, I tried to store already serialized default value on field deconstruction and added test cases mimicking field serialization step in migrations. This is already uploaded on PyPI
