### ISSUE TITLE
Pydantic V2 preliminary support

### ISSUE THREAD

**Issue by surenkov** [surenkov/django-pydantic-field#16]
Investigate the possibility of pydantic v2 usage as long as it goes to RC

**Comment by mihow** [comment]
Looking forward to this! Thanks for such a great library.

**Comment by surenkov** [comment]
> Looking forward to this! Thanks for such a great library.

Hey @mihow, thank you! I opened a draft PR #34, you can subscribe to it to get notified once v2 support is ready.

I thought a little bit, and planning to publish v0.3.0 once the PR is merged. It will contain adapters both for Pydantic v1 and v2, though v1 implementation will be in maintenance-only mode, to focus on v2 support for the future.
