### ISSUE TITLE
field lookups no longer work.

### ISSUE THREAD

**Issue by krs23** [surenkov/django-pydantic-field#21]
since last version(s) the field lookup from JSONField doesnt work any more for me.

i.e with.
```

class MySchema(BaseModel):
  required: bool = True

>>> Model.objects.filter(config__required=True)
ValidationError: 1 validation error for FieldSchema[MySchema]
__root__
  value is not a valid dict (type=type_error.dict)
```

**Comment by krs23** [comment]
Just adding a` try: ... except: return prep_value ` around row 86-89 in fields.py fixed the issue but not pretty

**Comment by surenkov** [comment]
Hi @krs23, thanks for pointing it out!

This is yet another regression that has appeared in django 4.2 and the way it handles json fields internally.
I prepared the PR, but frankly speaking I'm not really fond of it -- don't see the feasible way to handle it in any other way than the `try...except' you suggested (just hidden inside of `SchemaEncoder`). 

--
There is actually one possible way of handling such a thing -- get pydantic to perform a partial model validation, although it is not possible to achieve this out of the box, and implementing it myself will require a significant amount of engineering. 
There are a few requests for this feature, but I don't think it's anywhere near in the roadmap, and most likely will only appear in [pydantic V2](https://github.com/pydantic/pydantic/issues/1673#issuecomment-1428249907).

**Comment by surenkov** [comment]
Uploaded `v0.2.6` to PyPI containing a fix.
Also added a few integration tests to make sure it properly handles lookups across SQLite, PostgreSQL and MySQL.
