### ISSUE TITLE
ImportError with pydantic 1.9.1

### ISSUE THREAD

**Issue by Arondit** [surenkov/django-pydantic-field#24]
Trying to use this lib with pydantic==1.9.1 leads to import error. 
`ImportError: cannot import name 'get_config' from 'pydantic.config'`
In 1.9.1 there is no this function, you can check it here https://github.com/pydantic/pydantic/releases/tag/v1.9.1

If you don't want to fix backward compatibility so far, you could just fix required version of pydantic.

**Comment by surenkov** [comment]
Hi @Arondit, thank you for pointing out on this issue.

I just released [v0.2.8](https://github.com/surenkov/django-pydantic-field/releases/tag/v0.2.8) with added (and tested on current test suite) support of pydantic 1.9.*; feel free to reopen this ticket if you find out anything else specific to this release.
