### ISSUE TITLE
PEP 561 Compliance

### ISSUE THREAD

**Issue by Mshivam2409** [surenkov/django-pydantic-field#39]
Hey, first of all, thank you so much for this awesome package.

The package is mostly completely typed, but the absence of a `py.typed` marker raises errors with mypy. Would it be possible to add a marker to make it PEP 561 compliant?

**Comment by surenkov** [comment]
Hi @Mshivam2409, thanks for reporting this.

Added this marker to the package, will be delivered to PyPI with the following release.
