### ISSUE TITLE
Cannot use django bulk_update when model has a SchemaField

### ISSUE THREAD

**Issue by zoestoll** [surenkov/django-pydantic-field#46]
I cannot use Django's `bulk_update` on a model that uses django-pydantic-field SchemaField.
I'm not sure if this is django-pydantic-field or django problem.

Repro:

```
class ExampleSchemaField(BaseModel):
    count: int

class Example(models.Model):
    example_field: ExampleSchemaField = SchemaField(default=ExampleSchemaField)

e = Example.objects.create({"count": 1})
Example.objects.bulk_update([e], ["example_field"])
```

This throws `TypeError: Object of type Case is not JSON serializable`. 

It works fine when updating _without_ `bulk_update`:
```
e = Example.objects.create({"count": 1})
e.example_field = {"count": 2}
e.save()
```

And bulk_create seems to work as well.

**Comment by surenkov** [comment]
Hey @zoestoll, thank you for reporting this!

AFAIK, this issue is related only to pydantic v1 implementation.
Will dig deeper into that, apparently this is a high priority issue to fix...

**Comment by surenkov** [comment]
@zoestoll I have pushed v0.3.1 to PyPI with a potential fix, could you please check that out?
Closing this issue for now, feel free to reopen it if needed.
