### ISSUE TITLE
Cooperation with other repository `django-jsonform` for widget

### ISSUE THREAD

**Issue by sshishov** [surenkov/django-pydantic-field#55]
Hi dear maintainer, I am creating this ticket just to notify about possible extension of your repo by cooperating with the following repo: https://github.com/bhch/django-jsonform/

It has the ability to create very functional widgets for JSON schema which is very convenient for forms and django-admins.

Having great FE UI for django-admin and ordinary forms is essential to build functional project. Therefore mentioning or adding HOWTO with example of collaboration of these 2 projects would be beneficial, imho.

**Comment by surenkov** [comment]
@sshishov that's the great idea, agree this is something worth spending the time on integration!

Don't have any good estimates though, there's a #44 which is also long awaited by the devs.

**Comment by surenkov** [comment]
Apparently, at least for simple schemas, it appeared to be working, and I'm impressed with the functionality. Thank you for the suggestion!

The aspect I'm uncertain about is the method for toggling between standard and `jsonform` widgets.
In PR #59, the approach is contingent on import paths and the presence of `django_jsonform` in the installed apps. However, overriding the default behavior may not be ideal, and it might be better to specify `ModelForm.Meta.field_classes`/`widgets` or `ModelAdmin.formfield_overrides` directly.

I'm open to discussing this further and would appreciate on any input.

<img width="856" alt="Screenshot 2024-04-01 at 01 38 04" src="https://github.com/surenkov/django-pydantic-field/assets/942909/d7a48fdc-4cb8-4bcd-a50d-f1ddb3cd4bd7">

<img width="895" alt="Screenshot 2024-04-01 at 01 38 12" src="https://github.com/surenkov/django-pydantic-field/assets/942909/0a5cf695-7f67-4801-bee0-eb2194fe1f41">

**Comment by surenkov** [comment]
Played around with it a bit, and came up with pluggable widget overrides, e.g.:

```python
from django.forms import Form
from django_pydantic_field.forms import SchemaField
from django_jsonform.widgets import JSONFormWidget

class SchemaModelForm(Form):
    field = SchemaField(schema=..., widget=JSONFormWidget)
```
and
```python
from django.contrib import admin
from django_pydantic_field.v2.fields import PydanticSchemaField
from django_jsonform.widgets import JSONFormWidget

@admin.site.register(SchemaModel)
class SchemaModelAdmin(admin.ModelAdmin):
    formfield_overrides = {
        PydanticSchemaField: {"widget": JSONFormWidget},
    }
```

IMHO, this should be a better approach than unconditionally override the default form field behaviours.

**Comment by conradlee** [comment]
In the code above what is `SchemaModel`?  It is not defined.  Should this be the pydantic schema that we're using for the schemafield?
