### ISSUE TITLE
HttpUrl or any other pydantic specific field is not serializable

### ISSUE THREAD

**Issue by sshishov** [surenkov/django-pydantic-field#56]
If we have a pydantic model with any Pydantic specific fields, then the model will not be properly serialized and the crash will appear.

For instance:
```python
import pydantic
import django_pydantic_field

class MyModel(pydantic.BaseModel):
     my_url: pydantic.HttpUrl = pydantic.HttpUrl('https://example.com/')

obj = MyModel()
field = django_pydantic_field.SchemaField(schema=MyModel)
field.get_prep_value(obj)
```
And the output will be:
```python
TypeError: Object of type Url is not JSON serializable
```

It can be fixed if we use the `mode=json` when we perform `_prepare_raw_value` inside `get_prep_value` like this:
```python
def get_prep_value(self, value: t.Any):
        value = self._prepare_raw_value(value, mode='json')
        return super().get_prep_value(value)
```

Or am I missing something?

**Comment by surenkov** [comment]
Yep, you're absolutely correct, thank you for reporting this!

I've prepared the fix in #57, will release it under the next patch.
