### ISSUE TITLE
Weird return format in DRF

### ISSUE THREAD

**Issue by andreasnuesslein** [surenkov/django-pydantic-field#61]
Ahoy there,

first of: thanks for this package :black_heart:  

I have a situation which might be pebkac, but at this point I figured I'd better ask:

Situation:
```python
class CurrentDateAreaSchema(pydantic.BaseModel):
    current: bool
    date: str
    area: Decimal

contract_size = SchemaField(
    schema=list[CurrentDateAreaSchema], blank=True, default=list
)
```

It works nicely and saved the right information into the database; however when I return it via normal DRF `ModelViewset` and `ModelSerializer` logic I get this: 
```json
"contract_size": [
  [
    ["current",false],
    ["date","2022"],
    ["area",1104]
  ],
  [
    ["current",true],
    ["date","2024"],
    ["area",3306.9]
  ]
],
```

I would rather like to have 
```json
"contract_size": [
  {
   "current":false,
   "date":"2022",
   "area":1104
  },
  {
    "current":true,
    "date":"2024",
    "area":3306.9
  }
],
```

Is the former intended behaviour? Or am I missing something?

Thanks!

**Comment by andreasnuesslein** [comment]
Damn, I knew it was pebkac. So imported the wrong SchemaField here:
```python
class MyModelSerializer(serializers.ModelSerializer):
    foo_field = SchemaField(schema=Foo)
```

`from django_pydantic_field import SchemaField` instead of `from django_pydantic_field.rest_framework import SchemaField`


Anyways: It's kind of tedious to repeat like 30 field definitions here in my serializer. Could there be a way to return the dict-format by default? 

Cheers

**Comment by surenkov** [comment]
Hey Andreas, thank you for raising this up.

> Anyways: It's kind of tedious to repeat like 30 field definitions here in my serializer. Could there be a way to return the dict-format by default?

I know this is a bad dev experience in the serializers :(
I dug through the DRF codebase a wile ago and was not able to find a good solution for different DRF versions for this problem except of inheriting from `ModelSerializer` (or writing a mixin) and overriding custom field types handling.

For the time I initially implemented this package, this was something I didn't take too much into consideration, but probably now it could be a good addition to the package.

**Comment by andreasnuesslein** [comment]
Hi @surenkov ,

thank you for your response!

I wonder: is there any scenario where you prefer to get that list-of-lists (or list-of-tuples) format? Or what was the design decision to output this?  Only if it's not too much trouble :hugs: 

By the way, this is not perfect but anyways, here's how I also then gave DRF Spectacular the right hints:
```python
@extend_schema_field(schema.CurrentDateAreaSchema)
class CurrentDateAreaSchemaField(SchemaField):
    def __init__(self, *args, **kwargs):
        super().__init__(schema=schema.CurrentDateAreaSchema, *args, **kwargs
        

class MyModelSerializer(serializers.ModelSerializer):
    contract_size = CurrentDateAreaSchemaField()    
```

**Comment by surenkov** [comment]
@andreasnuesslein thank you for suggestion on `drf-spectacular`. I honestly didn't have a chance yet to look on the integration, but your suggestion looks very promising.

Regarding deviated representations -- that's something unexpected.

`django_pydantic_field.SchemaField` is a subclass of `django.db.models.Field`: it is intended to be used directly on the Django models, like `django.db.models.JSONField` but with coersion to the specified schema, unlike `django_pydantic_field.rest_framework.SchemaField`, which is a DRF serializer field only.

I did not expect that it would work with serializers and cause such interesting side effect. Though Python's dynamic nature can lead to the fact that these two fields are nominally combatible, at least in DRF scope, but naturally they should not be interchangeable...

**Comment by andreasnuesslein** [comment]
Hi @surenkov ,
 sorry I totally dropped the ball about the serialization thing :see_no_evil:  Thank you for explaining, but I somehow got it into my mind that the "default" serializer would produce this list of tuples. I understand now it's because of using the wrong serializer and python just accepting it and trying to go with it.

If I get a minute, maybe I can also write a more generic version of what I have above. I'll let you know!

Cheers

**Comment by surenkov** [comment]
@andreasnuesslein thank you for taking your time on that!

if you don't mind, I'm closing this issue for now.

**Comment by andreasnuesslein** [comment]
continued this train of thought in #44
