### ISSUE TITLE
Posibility to omit a fields in the resulting JSON when it's unset?

### ISSUE THREAD

**Issue by andreasnuesslein** [surenkov/django-pydantic-field#62]
Hi @surenkov 

I have another question regarding your pydantic field :)

I'm creating a BaseModel like so:
```python
I18NSchema = create_model(
    "I18NField",
    __config__={"extra": Extra.forbid},
    **{
        lang[0]: (
            str,
            Field(default=None, description=f"Translation in {lang[0].upper()}"),
        )
        for lang in settings.LANGUAGES
    },
)

```

which basically results in a:
```python
class I18NSchema(BaseModel):
    en: str = None
    fr: str = None
    ...
```

(I initially tried it with `default=""` too)

Is there a way to **not** have this in the database in the end: 
```json
{"af": null, "ar": null, "en": "hello", "es": null, "fr": "bonjour", "km": null, "lo": null, "mn": null, "pt": null, "ru": null, "th": null, "zh": null}
// respectively:
{"af": "", "ar": "", "en": "hello", "es": "", "fr": "bonjour", "km": "", "lo": "", "mn": "", "pt": "", "ru": "", "th": "", "zh": ""}
```

but only the keys that were actually set, i.e. in this case: `{"en": "hello", "fr": "bonjour"}`

thanks a bunch!

**Comment by andreasnuesslein** [comment]
(i'm guessing this discussion here is related to that: https://github.com/pydantic/pydantic/issues/1223  and I feel like there's no easy way)

**Comment by surenkov** [comment]
Hi Andreas,

I think you can pass `exclude_defaults` / `exclude_unset` / `exclude_none=True` <https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.model_copy>, depending on your requirements to the field kwargs, e.g.:

```python

class ConfigModel(models.Model):
	l18n_config = SchemaField(schema=I18NSchema, exclude_unset=True)
```

**Comment by surenkov** [comment]
Hi @andreasnuesslein 

I think you can pass [`exclude_defaults` / `exclude_unset` / `exclude_none=True`](https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.model_copy), depending on your requirements to the field kwargs, e.g.:

```python

class ConfigModel(models.Model):
    l18n_config = SchemaField(schema=I18NSchema, exclude_unset=True)
```

**Comment by andreasnuesslein** [comment]
!! perfect, thanks so much. totally solved exactly my situation. I feared I had to define "extras.Allow" and then dynamically parse extras etc. this is way better! :)
