### ISSUE TITLE
Support for drf-spectacular

### ISSUE THREAD

**Issue by holtgrewe** [surenkov/django-pydantic-field#67]
Thank you for this wonderful package.

I'd like to get support for `drf-spectacular` rather than the builtin schemas. Apparently, DRF will remove the builtin schemas in the future.

> Deprecation notice:
>
> REST framework's built-in support for generating OpenAPI schemas is deprecated in favor of 3rd party packages that can provide this functionality instead. The built-in support will be moved into a separate package and then subsequently retired over the next releases.
>
> As a full-fledged replacement, we recommend the [drf-spectacular](https://drf-spectacular.readthedocs.io/en/latest/readme.html) package. It has extensive support for generating OpenAPI 3 schemas from REST framework APIs, with both automatic and customisable options available. For further information please refer to [Documenting your API](https://www.django-rest-framework.org/topics/documenting-your-api/#drf-spectacular).
> 
> -- https://www.django-rest-framework.org/api-guide/schemas/

Would that be possible?

**Comment by surenkov** [comment]
@holtgrewe we track `drf-spectacular`-related progress in #44 with community efforts to make its integration more-or-less seamless, but unfortunately I don't have much time to spend on it, at least not this month.

I would be glad of any help related to this integration. Closing this in favor of #44
